### ISSUE TITLE
Initial API Design

### ISSUE THREAD

**Issue by rpwagner** [sdsc/nucleus-roll#1]
To drive the design of client and infrastructure code @dimm0 has committed (8e78b37837ee941624ac5749e453823a4e8b6d02) an initial draft of the REST API for the management interface. I'd like us to flesh this out a bit more, since it will help us be clear on what resources (clusters, nodes, etc.) users will be interacting with and what actions they can take on them. Recall from our earlier conversations that the API should mask as many details of the supporting infrastructure as possible. Once we agree on a first draft we'll likely stub out an initial implementation and then begin filling in the client and infrastructure support.

For reference, I uploaded a [slide deck](https://github.com/sdsc/nucleus-roll/blob/master/doc/WagnerCometCloudTraining.pdf) I gave at XSEDE15.

**Comment by laszewsk** [comment]
Proposal: timed reservation

I suggest to integrate my reservation interface. As said we have REST for this, but it seems that current resources do not have start and end time.

There is a question if we consider a reservation as a resource and associate another resource with a named reservation. This may make a lot of sence.
Maybe I overlooked how you do timer reservations.

**Comment by laszewsk** [comment]
Proposal: rename clust to cluster or vcluster

**Comment by rpwagner** [comment]
@laszewsk  I agree that cluster is clearer than "clust" and we don't need to conserve characters.

**Comment by rpwagner** [comment]
@laszewsk , the reservations seem like subresource of a cluster. Something that the current draft doesn't make clear is how a user requests one more virtual cluster nodes to be launched at any time. The power on action for a node could cover this, but it doesn't cover the "please boot 4 nodes anytime" case. Is your reservation interface intended only for launching specific nodes at a specific time?

**Comment by ppapadopoulos** [comment]
Reservations:  I would divide into two use cases.
1.  Boot node(s).  Destroy after N hours (minutes), if not already dead (limit charging)
2.  Boot node(s) at wall clock time T, destroy after N hours (minutes), if not already dead.

What we haven't discussed is which booting cases should be supported first, and then eventually.
e.g.
1.  Boot N nodes or boot none
2.  Boot at least K nodes but not more than N.
3.  Boot N nodes or boot none within X minutes of request
4.  Boot at least K nodes but not more than N within X minutes of request
5.  Boot N nodes or none at Timestamp T with variation no greater than v minutes
6.  Boot at least K nodes but no more than N at Timestamp T with variation no greater than v minutes

case 1 and 2 both capture. boot a single node.  Both are standard batch in that the request is fulfilled on a best effort basis.

**Comment by ppapadopoulos** [comment]
More on booting and naming.
1). It's a cluster. It has a frontend/master/head node. The API should be explicit in identifying this particular resource.   It has a special configuration in comparison to other nodes within the cluster
2) I don't llike the name "VMs",  again it's a cluster.  They can simply be nodes or virtual nodes

Booting.  You rarely boot a cluster "all at once".  Typically you boot a frontend, then nodes in a particular sequence for discovery.   That part needs thinking about more deeply.

Booting part 2.   Any node (frontend or node) can be boot from hard disk, network, or cdrom image. There are two scenarios:  1. get and set the default boot sequence for a node.  2. set a one time temporary boot device.

Rebooting: also known as power cycling.  That's a different action than a boot.

**Comment by laszewsk** [comment]
yes i was thinking about booting multiple clusters by a user.
This is actually a requirement in my case as I may need a production machine and also a development machine. So i keep the production cluster up till i managed to verify that my new “test” cluster is oc and than i just go and 

a) replace the production cluster nodes
b) shout down the production cluster and boot it with the new software (e.g. get a new reservation)

In either case we have start and endtime

**Comment by ppapadopoulos** [comment]
Elements of API available to end user.

we need to mark which elements of the API are available to the end user.  A large number of the disk-image related items are not available to the end user and should be completely opaque to them (they can't create new clusters, they can't create new storage for example). 

Be mindful of "mission creep".  While it might be nice to allow users to define snapshots of their disks, that's probably not a Jan 1 capability.  If it were, then I would only support user-defined snapshots when a particular node is at rest, and it's disk is back in the virtual disk vault.   

Reverting a node to snapshot would require a node shutdown, revert, and then reboot.   Doing that requires interaction with the scheduling system to not remove the virtual node when it powers off.

**Comment by laszewsk** [comment]
we use hostlists in arguments not just simple hostnames

reboot server[001-003] 

would reboot the 3 servers specified

delete server[001-003] 

would delete the servers and return them to the pool of available resources/servers

boot server[001-003] does a boot

```
as Philll says we need some parameters in each one of them
```

naturally this could also mean we support ip host lists

```
reboot 198.127.127.[011-014]
```

commands are only appied if you authorized and own the resources.

**Comment by laszewsk** [comment]
i agree, we need to augment api and commands with timeline

**Comment by rpwagner** [comment]
@laszewsk, @ppapadopoulos I've got a rough timeline laid out that can be converted to milestones. We can then map the API to the milestones we think are appropriate.

**Comment by rpwagner** [comment]
A specific comment about the document format for whomever wants to take on the changes, let's make it tabular with these additional columns:
- Milestone
- User Accessible

This will help with the development process and separating user and admin functionality.
