### ISSUE TITLE
Command line interface

### ISSUE THREAD

**Issue by laszewsk** [sdsc/nucleus-roll#10]
We need a commandline interface that uses the rest service. 
- [x] initial design will not use security, we assume command is run behind firewall by authorized users
- [x] advanced design (next year) introduction of roles
- [x] advanced design (next year) introduction of token based authentication
- [x] integration of yubikeys

**Comment by laszewsk** [comment]
An initial design was added for the command documentation while transforming the reservation into vcluster command.

**Comment by rpwagner** [comment]
@laszewsk, we can discuss the access to the REST API in our meeting tomorrow. My preference is to secure it from the beginning to allow external clients to access it, rather than require users to log in to Comet unnecessarily.

**Comment by dimm0** [comment]
Done
