### ISSUE TITLE
Boot N Nodes via API

### ISSUE THREAD

**Issue by rpwagner** [sdsc/nucleus-roll#2]
The most basic case of launching a virtual cluster. Given an existing (provisioned) cluster with at least N idle nodes, a user submits a request to boot N nodes. The nodes are booted using only Rocks (no scheduler).

**Comment by tcooper** [comment]
Two additional constraints on the use case that currently matter...
- Have the virtual cluster nodes **ever** been booted before?
- Have the virtual cluster nodes been installed?

**Comment by rpwagner** [comment]
> Given an existing (provisioned) cluster with at least N idle nodes, a user submits a request to boot N nodes.

I'm using the term _provisioned_ to mean installed and ready to run and _idle_ means the disk image is sitting on the image repository unattached. So yes to both.

**Comment by dimm0** [comment]
Done
